// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mlghynmgvftwegixyadd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1sZ2h5bm1ndmZ0d2VnaXh5YWRkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4Njk0MTgsImV4cCI6MjA2NjQ0NTQxOH0.CTOr-yUUWX2JrVON4XNnkH31vsPSy9B0uZPl05FfNtQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);